version: '{build}'
build_script:
  - npm install
  - npm run dist
cache:
  - node_modules
artifacts:
  path: dist/*.exe
deploy:
  release: $(appveyor_repo_tag_name)
  description: 'Automated release $(appveyor_repo_tag_name)'
  provider: GitHub
  auth_token:
    secure: zJZKDKcrd4i1a8WMLt0XIn0MirI3OglJKNG7rWxysFCw1lbsfUJNBUrcVT0vNh8y
  artifact: /dist\/.*\.exe/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only
